### PR TITLE
Limit split for string keywords

### LINKED ISSUE #95: Pattern keyword do not appear when = character is in regex
As the title suggests, adding an = character in the regex seems to break the reflector. Using jsonschema_extras instead as a workaround is not ideal as it doesn't parse escaped commas.

Example:
Using this struct
```
type S struct{
	Normal string `jsonschema:"pattern=$\\,=^"`
	Extras string `jsonschema_extras:"pattern=$\\,=^"`
	NoEquals string `jsonschema:"pattern=$\\,^"`
}
```

Generates this schema
```
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$ref": "#/$defs/S",
    "$defs": {
        "S": {
            "properties": {
                "Normal": {
                    "type": "string"
                },
                "Extras": {
                    "type": "string",
                    "": "^",
                    "pattern": "$\\"
                },
                "NoEquals": {
                    "type": "string",
                    "pattern": "$,^"
                }
            },
            "additionalProperties": false,
            "type": "object",
            "required": [
                "Normal",
                "Extras",
                "NoEquals"
            ]
        }
    }
}
```

### PR DESCRIPTION
**Pull request by Hotdawg**
Fixes #95

There are probably other places where limiting split makes sense (e.g. arrayKeywords), but this PR focuses on the pattern keyword specifically.

### CODE REVIEW

**Review by samlown — CHANGES_REQUESTED** [review]
Thanks for this! looks good, just a Linter issue to fix before we can merge.

**Comment by Hotdawg** [comment]
Should be fixed now

**Review by samlown — APPROVED** [review]
Nice! Thanks!

**Comment by samlown** [comment]
Sorry @Hotdawg, looks like the tests are failing now :-(

**Comment by Hotdawg** [comment]
Updated the branch with latest, Fixed failing tests.
tests and linter passes on my machine

**Pull request merged**
