### PR TITLE
Use allOf to amend schema referred to with $ref

### PR DESCRIPTION
**Pull request by arvidfm**
This PR makes it so that if a schema referenced using `$ref` also has attributes provided using the `jsonschema` tag, the attributes will be merged using `allOf` instead of putting the attributes in the same object as the `$ref`. This allows for proper merging of the original schema and the explicitly provided attributes. (In my use case, it makes the attributes display properly in Redocly.)

For reference, see: https://github.com/OAI/OpenAPI-Specification/issues/1514

Example structs:
```go
// A user.
type User struct {
	Name string `json:"name" jsonschema:"description=Name of user"`
}

// A file.
type File struct {
	Owner User `json:"owner" jsonschema:"description=The owner of this file"`
}
```

Without changes:
```json
{
  "$schema": "http://json-schema.org/draft/2020-12/schema",
  "$ref": "#/$defs/File",
  "$defs": {
    "File": {
      "properties": {
        "owner": {
          "$ref": "#/$defs/User",
          "description": "The owner of this file"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "owner"
      ],
      "description": "A file."
    },
    "User": {
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of user"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name"
      ],
      "description": "A user."
    }
  }
}
```

With changes:
```json
{
  "$schema": "http://json-schema.org/draft/2020-12/schema",
  "$ref": "#/$defs/File",
  "$defs": {
    "File": {
      "properties": {
        "owner": {
          "allOf": [
            {
              "$ref": "#/$defs/User"
            },
            {
              "description": "The owner of this file"
            }
          ]
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "owner"
      ],
      "description": "A file."
    },
    "User": {
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of user"
        }
      },
      "additionalProperties": false,
      "type": "object",
      "required": [
        "name"
      ],
      "description": "A user."
    }
  }
}
```

### CODE REVIEW

**Review by samlown — CHANGES_REQUESTED** [review]
Thanks for putting the effort in here, but I don't think we can accept this proposal in its current state. Firstly, all the tests and linters are failing. Secondly, I don't think this is good usage of the `allOf` property, which is intended for schemas that match all of a set of different sub-schemas. You might want to see if it's easier to fix Redocly instead of applying changes here.

I'd also add that `allOf` is hard to implement in Go, and not common usage. Go likes things to be explicit. Matching a struct between different sub-schema, aside from the confusion, would be hard.

**Comment by arvidfm** [comment]
I'm happy to look at fixing the linting issues, though of course if you think the approach in incorrect to begin with there's little point. Do you have any suggestion on how to solve this otherwise then, since jsonschema currently generates an invalid schema if you provide extra information in struct tags (or at least, any additional properties other than `$ref` will be ignored according to the spec, and it appears that it will cause warnings in some editors)?

The reason I picked this approach is to make sure that the resulting schema is always valid, and it was suggested by one of the OpenAPI developers in the linked issue.

**Comment by arvidfm** [comment]
> A good intermediary fix to comply with the specs would be to disallow any additional properties in the schema and only use the $ref.

I'm not a big fan of this, since it would result in different behaviour/semantics depending on if you're using referencing or not.

> Another, more complex, option would be to detect if additional properties are defined and spin them into an allOf schema array.

That's what I tried to implement with this PR, or am I misunderstanding what you mean?

**Comment by samlown** [comment]
I've had chance to look at the latest specs: https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-01

There is no mention of fields defined alongside `$ref` not being valid, indeed, the document actually _includes_ examples usages of `$ref` and `description` with exactly this use-case. Looking at the OpenAPI specification and the issue you posted, they seem to be in a right mess with this.

My strong recommendation would be to manually avoid adding `description`, or use the `JSONSchema()` method if you need to do stuff with OpenAPI. Otherwise, I strongly believe this implementation should stick to the guidance of the specs, and not over-complicate things.

Sorry if that's not quite what you were expecting!

**Comment by arvidfm** [comment]
Yes, I had a closer look at the (very confusing) OpenAPI issue, and it seems that for OpenAPI 3.1 specifically, they're using a version of JSON Schema where declaring fields alongside `$ref` should work, in some circumstances at least. If I understand it correctly, apparently newer versions of JSON Schema allow overriding referenced schemas using sibling fields, while older versions don't? I'm using Redocly to generate API documentation and apparently they fixed a bug relating to not handling this case properly literally yesterday.

So I suppose depending on what version of JSON Schema you're targetting, this PR may or may not be needed. Perhaps it should be possibly to include a keyword saying that any keywords that follow should be moved to a separate `allOf` entry... I'm thinking something like `jsonschema:"allOf,description=Description,..."` and then we would look for that `allOf` keyword before checking any other keywords. That way you could choose yourself whether to separate the keywords, depending on the version of OpenAPI/JSON Schema/Redocly/etc you happen to be using.

If you're interested in something along these lines, I'm happy to update this PR to do so. Otherwise, I'll just close this as I imagine proper support for fields alongside `$ref` should trickle in over the coming months in various projects.

**Pull request closed without merging**
