### PR TITLE
fix: Process only unprocessed tags in recursion

### PR DESCRIPTION
**Pull request by candiduslynx**
Regression from #101

### CODE REVIEW

**Comment by candiduslynx** [comment]
@samlown I've tested our case with this code & it works OK (apart from #102), so I'd love to get a release after the PR is merged

**Comment by candiduslynx** [comment]
@samlown is there any chance of review this week?

**Review by samlown — APPROVED** [review]
LGTM

**Comment by candiduslynx** [comment]
@samlown could you also create a tag/release?

**Pull request merged**
