### PR TITLE
implement Reflector.KeyNamer

### LINKED ISSUE #15: Transform struct keys before generating the JSON schema
In my application, I transform struct keys to snake_case before writing a JSON file.

For this, I use [json-iterator](https://github.com/json-iterator/go)'s `RegisterExtension` to [rename keys to snake_case](https://gist.github.com/ewen-lbh/ad7750f562a319f81ccc05d08512a24b)

But right now, it doesn't seem possible to reflect that using this package.

What I'd like is a new option for the `Reflector` type, something like `TransformKeys`, of type `func(string) string` that gets run on every struct key before generating the  schema.

This would be like a "key name" equivalent of `Namer`, basically.

I might actually do a PR, it doesn't seem that complicated to implement.

### PR DESCRIPTION
**Pull request by ewen-lbh**
Closes #15 

Let me know if the test I added does not belong here

### CODE REVIEW

**Review by samlown — APPROVED** [review]
Looks good! Thanks! I'd suggest adding a quick example to the "test table" and fixtures, for the sake of completeness, as they're a bit easier to update. I'm okay to accept this as-is however.

**Review by samlown — CHANGES_REQUESTED** [review]
Changing status until lint issues are fixed.

**Comment by ewen-lbh** [comment]
I saw the lint error, and yes, it felt a bit unnatural to put the test here.

Just to make sure I understood correctly, I'll move the test to /reflect_test.go and put the expected output at fixtures/keynamed.json

(Let me know if you have a better idea for the JSON file name, I just put what I had off the top of my head)

**Comment by ewen-lbh** [comment]
I almost forgot about the most important thing: documentation!

**Review by samlown — APPROVED** [review]
Looks great! Thanks!

**Pull request merged**
